In [1]:
#numerical python
#list ---> 4000 / matrix ---> 1000x1000

In [2]:
import  numpy as np

In [5]:
np.__version__

'2.1.3'

In [6]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [7]:
d = a.ndim
d

1

In [9]:
s = a.size
s

3

In [10]:
b = np.array([[1, 2, 3],
             [4, 5, 6]], dtype=np.int32)
bd = b.ndim
bd

2

In [11]:
bs = b.shape
bs

(2, 3)

In [12]:
bsi = b.size
bsi

6

In [13]:
bdt = b.dtype
bdt

dtype('int32')

In [14]:
#[[1, 2, 3], [4, 5, 6]]
#house : [area, floor, age]
#house1: [25, 3, 45]
#house2 = [148, 1, 3]...

#1, 2, 4
#4, 5, 5
#...

In [15]:
z = np.zeros((2, 3))
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
o = np.ones((4, 5))
o

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
f = np.full((2,7), 8)
f

array([[8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8]])

In [20]:
ar = np.arange(0, 18, 2)
ar

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [24]:
ls = np.linspace(0, 1, 5)
ls

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [25]:
ls = np.linspace(0, 1, 6)
ls

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [28]:
b = np.array([[1, 2, 3],
             [4, 5, 6]], dtype=np.int32)
a = b.astype(np.float32)
a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [30]:
s = a.shape
s

(2, 3)

In [31]:
ad = a.ndim
ad

2

In [32]:
sa = a.size
sa

6

In [36]:
v = np.arange(1, 13)
print(v)
k = v.reshape(3, 4)
k

[ 1  2  3  4  5  6  7  8  9 10 11 12]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
k2 = v.reshape(4, 3)
k2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])