In [1]:
import numpy as np

## View

In [2]:
a = np.array([
    [1, 2, 4],
    [4, 5, 6]
])

In [3]:
a.ndim

2

In [4]:
b = a[0:, 0:2]
b

array([[1, 2],
       [4, 5]])

In [6]:
b[0, 0] = 0
b

array([[0, 2],
       [4, 5]])

In [7]:
b[0, 0] = b[0, 0] + 1
b

array([[1, 2],
       [4, 5]])

In [8]:
a

array([[1, 2, 4],
       [4, 5, 6]])

## Copy

In [10]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
b = a[0:, 0:2].copy()
b[0, 0] = 0

print(b)
print(a)

[[0 2]
 [4 5]]
[[1 2 3]
 [4 5 6]]


In [12]:
b

array([[0, 2],
       [4, 5]])

## Sum

In [13]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
t = np.sum(a)
t

np.int64(21)

In [32]:
v = np.sum(a, axis=0) #axis=0 --> columns
v

array([5, 7, 9])

In [16]:
h = np.sum(a, axis=1) #axis=1 --> rows
h

array([ 6, 15])

## Mean

In [18]:
k = np.array([1, 2, 3])
average = np.mean(k)
average

np.float64(2.0)

In [21]:
u = np.array([[1, 2, 3],
              [4, 5, 6]])
avg_2d = np.mean(u) # (1+2+3+4+5+6)/6
avg_2d

np.float64(3.5)

In [22]:
avg_2d_col_mean = np.mean(u, axis=0)
avg_2d_col_mean # (1+4)/2 : 2.5

array([2.5, 3.5, 4.5])

In [24]:
m_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[11, 12, 13], [14, 15, 16]]
])
m_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]]])

In [25]:
m_3d.ndim

3

In [26]:
m_3d.shape

(2, 2, 3)

In [27]:
avg_3d = np.mean(m_3d)
avg_3d

np.float64(8.5)

In [30]:
avg_3d_axis0 = np.mean(m_3d, axis=0)
avg_3d_axis0

array([[ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [31]:
avg_3d_axis2 = np.mean(m_3d, axis=2)
avg_3d_axis2

array([[ 2.,  5.],
       [12., 15.]])

## Var (variance is a fundamental measure that quantifies the spread of a set of numbers.)

In [33]:
g = np.array([1, 2, 3])
var_g = np.var(g)
var_g

np.float64(0.6666666666666666)

## Std (Standard Deviation)(calculates the NumPy standard deviation of given data along a specified axis.)

In [34]:
h = np.array([14, 15, 16])
std_h = np.std(h)
std_h

np.float64(0.816496580927726)

## Prod (used to calculate the product of array elements over a specified axis.)

In [36]:
h = np.array([14, 15, 16])
prod_h = np.prod(h)
prod_h

np.int64(3360)

## Min / Max

In [37]:
h = np.array([14, 15, 16])
h_min = np.min(h)
h_min

np.int64(14)

In [38]:
h_max = np.max(h)
h_max

np.int64(16)

In [39]:
m_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[11, 12, 13], [14, 15, 16]]
])

print(np.max(m_3d))
print(np.min(m_3d))

16
1


In [40]:
m_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[11, 12, 13], [14, 15, 16]]
])

print(np.amax(m_3d , axis = 0))
print(np.amin(m_3d))

[[11 12 13]
 [14 15 16]]
1


In [41]:
u = np.array([[1, 2, 3],
              [4, 0, 0]])
np.amax(u, axis=0)
#4
#3
#2

array([4, 2, 3])

In [42]:
u = np.array([[1, 2, 3],
              [4, 0, 0]])
np.amax(u, axis=1)


array([3, 4])

In [ ]:
# The End